import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";



export const metadata: Metadata = {
  title: "to do list(Designed by codeit)",
  description: "Generated by jisoleil",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
      <header className="py-2 pl-3" >
      <Link href="/">
      <Image src="/Size=Small.svg" width={71} height={40} alt="mobile-sized logo"/>
      </Link>
      </header>
      <hr></hr>
        {children}
      </body>
    </html>
  );
}
